---
# tasks file for roles/database

- name: DATABASE
  docker_container:
    name: database
    image: heavenshk/tp-devops-cpe:db
    state: started
    env:
      POSTGRES_DB: db
      POSTGRES_USR: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: app-network